"use client";

import Link from "next/link";
import { ArrowLeft, ArrowRight, CheckCircle2, Sparkles } from "lucide-react";
import { useParams } from "next/navigation";
import { useEffect, useState } from "react";
import { api, ApiError, Job, JobMatch } from "@/lib/api";

export default function JobDetail() {
  const { id } = useParams<{ id: string }>(); const jobId = Number(id); const [job, setJob] = useState<Job>(); const [match, setMatch] = useState<JobMatch>(); const [saved, setSaved] = useState(false); const [roadmap, setRoadmap] = useState(false); const [error, setError] = useState("");
  useEffect(() => { if (!Number.isInteger(jobId)) { setError("This job does not exist."); return; } let active = true; Promise.all([api.getJob(jobId), api.getJobMatch(jobId)]).then(([nextJob, nextMatch]) => { if (active) { setJob(nextJob); setMatch(nextMatch); } }).catch((reason: ApiError) => active && setError(reason.message)); return () => { active = false; }; }, [jobId]);
  const save = async () => { try { await api.createApplication(jobId); setSaved(true); } catch (reason) { setError(reason instanceof ApiError ? reason.message : "Could not save this application."); } };
  if (error && !job) return <div className="card p-6"><b>Unable to load this job.</b><p className="mt-2 muted">{error}</p><Link href="/dashboard/jobs" className="btn btn-secondary mt-4">Back to jobs</Link></div>;
  if (!job || !match) return <div className="card p-6 muted">Loading job details…</div>;
  return <><Link href="/dashboard/jobs" className="inline-flex items-center gap-2 text-sm font-bold text-brand"><ArrowLeft size={16} />Back to jobs</Link><div className="mt-6 grid gap-6 xl:grid-cols-[1.3fr_.7fr]"><section className="card p-6"><span className="grid h-12 w-12 place-items-center rounded-xl bg-mint text-lg font-bold text-brand">{job.company[0]}</span><h1 className="mt-5 text-3xl font-bold">{job.title}</h1><p className="mt-2 muted">{job.company} · {job.location}</p><div className="mt-7 border-t border-line pt-6"><h2 className="font-bold">Required skills</h2><div className="mt-3 flex flex-wrap gap-2">{job.skills.map(skill => <span key={skill} className="rounded-md bg-[#f1f5f4] px-3 py-1.5 text-sm">{skill}</span>)}</div></div></section><aside className="card overflow-hidden"><div className="bg-[#183735] p-6 text-white"><p className="text-xs font-bold text-[#bde6dc]">YOUR JOB MATCH</p><b className="mt-2 block text-5xl">{match.score}%</b><p className="mt-3 text-sm text-white/75">{match.explanation}</p></div><div className="p-6"><h3 className="text-sm font-bold">Strong match</h3><div className="mt-3 space-y-2">{match.strong.map(skill => <p key={skill} className="flex items-center gap-2 text-sm"><CheckCircle2 size={16} className="text-brand" />{skill}</p>)}</div><h3 className="mt-5 text-sm font-bold">Skill gaps to address</h3><div className="mt-3 flex flex-wrap gap-2">{match.missing.map(skill => <span key={skill} className="rounded-full bg-[#fff5e9] px-3 py-1 text-xs font-bold text-[#9a5b1d]">{skill}</span>)}</div>{roadmap ? <div className="mt-5 rounded-xl bg-mint p-4"><b className="text-sm">Learning roadmap ready</b><Link href="/dashboard/learning" className="mt-3 inline-flex text-sm font-bold text-brand">Open learning path <ArrowRight size={14} /></Link></div> : <button onClick={() => setRoadmap(true)} className="btn btn-secondary mt-6 w-full"><Sparkles size={16} />Improve my match</button>}<button onClick={save} disabled={saved} className="btn btn-primary mt-3 w-full">{saved ? "Application saved" : "Save application"}</button>{error && <p className="mt-3 text-sm text-[#a24747]">{error}</p>}</div></aside></div></>;
}
