from datetime import datetime
from sqlalchemy import Boolean, DateTime, Float, ForeignKey, Integer, JSON, String, Text
from sqlalchemy.orm import Mapped, mapped_column, relationship
from app.core.database import Base
class Timestamped: created_at: Mapped[datetime] = mapped_column(DateTime, default=datetime.utcnow); updated_at: Mapped[datetime] = mapped_column(DateTime, default=datetime.utcnow, onupdate=datetime.utcnow)
class User(Timestamped, Base):
    __tablename__='users'; id: Mapped[int]=mapped_column(primary_key=True); email: Mapped[str]=mapped_column(String(255),unique=True,index=True); full_name: Mapped[str]=mapped_column(String(120)); password_hash: Mapped[str]=mapped_column(String(255),default=''); role: Mapped[str]=mapped_column(String(30),default='job_seeker'); profile: Mapped['JobSeekerProfile']=relationship(back_populates='user',cascade='all, delete-orphan',uselist=False)
class JobSeekerProfile(Timestamped, Base):
    __tablename__='job_seeker_profiles'; id: Mapped[int]=mapped_column(primary_key=True); user_id: Mapped[int]=mapped_column(ForeignKey('users.id',ondelete='CASCADE'),unique=True); location: Mapped[str]=mapped_column(String(120),default=''); current_role: Mapped[str]=mapped_column(String(120),default=''); experience_years: Mapped[float]=mapped_column(Float,default=0); target_role: Mapped[str]=mapped_column(String(120),default='Backend Developer'); readiness_score: Mapped[int]=mapped_column(Integer,default=0); user: Mapped[User]=relationship(back_populates='profile'); skills: Mapped[list['UserSkill']]=relationship(back_populates='profile',cascade='all, delete-orphan')
class Skill(Timestamped, Base):
    __tablename__='skills'; id: Mapped[int]=mapped_column(primary_key=True); name: Mapped[str]=mapped_column(String(100),unique=True,index=True); category: Mapped[str]=mapped_column(String(50),default='Tools')
class UserSkill(Timestamped, Base):
    __tablename__='user_skills'; id: Mapped[int]=mapped_column(primary_key=True); profile_id: Mapped[int]=mapped_column(ForeignKey('job_seeker_profiles.id',ondelete='CASCADE'),index=True); skill_id: Mapped[int]=mapped_column(ForeignKey('skills.id')); score: Mapped[int]=mapped_column(Integer,default=0); verification_status: Mapped[str]=mapped_column(String(40),default='Self Reported'); evidence_count: Mapped[int]=mapped_column(Integer,default=0); profile: Mapped[JobSeekerProfile]=relationship(back_populates='skills'); skill: Mapped[Skill]=relationship()
class Job(Timestamped, Base):
    __tablename__='jobs'; id: Mapped[int]=mapped_column(primary_key=True); slug: Mapped[str]=mapped_column(String(120),unique=True,index=True); title: Mapped[str]=mapped_column(String(150),index=True); company: Mapped[str]=mapped_column(String(120)); location: Mapped[str]=mapped_column(String(120)); work_mode: Mapped[str]=mapped_column(String(30)); salary: Mapped[str]=mapped_column(String(80)); experience_min: Mapped[float]=mapped_column(Float,default=0); description: Mapped[str]=mapped_column(Text); requirements: Mapped[list['JobSkillRequirement']]=relationship(back_populates='job',cascade='all, delete-orphan')
class JobSkillRequirement(Base):
    __tablename__='job_skill_requirements'; id: Mapped[int]=mapped_column(primary_key=True); job_id: Mapped[int]=mapped_column(ForeignKey('jobs.id',ondelete='CASCADE'),index=True); skill_id: Mapped[int]=mapped_column(ForeignKey('skills.id')); required_level: Mapped[int]=mapped_column(Integer,default=60); is_required: Mapped[bool]=mapped_column(Boolean,default=True); job: Mapped[Job]=relationship(back_populates='requirements'); skill: Mapped[Skill]=relationship()
class Application(Timestamped, Base):
    __tablename__='applications'; id: Mapped[int]=mapped_column(primary_key=True); profile_id: Mapped[int]=mapped_column(ForeignKey('job_seeker_profiles.id',ondelete='CASCADE'),index=True); job_id: Mapped[int]=mapped_column(ForeignKey('jobs.id')); stage: Mapped[str]=mapped_column(String(30),default='Saved'); match_score: Mapped[int]=mapped_column(Integer,default=0)
class Resource(Timestamped, Base):
    __tablename__='resources'; id: Mapped[int]=mapped_column(primary_key=True); title: Mapped[str]=mapped_column(String(180)); resource_type: Mapped[str]=mapped_column(String(50)); skill_name: Mapped[str]=mapped_column(String(100),index=True); level: Mapped[str]=mapped_column(String(30)); url: Mapped[str]=mapped_column(String(500)); provider: Mapped[str]=mapped_column(String(100)); duration: Mapped[str]=mapped_column(String(40)); is_free: Mapped[bool]=mapped_column(Boolean,default=True); verified: Mapped[bool]=mapped_column(Boolean,default=True)
