"use client";

import Image from "next/image";
import Link from "next/link";
import { usePathname } from "next/navigation";
import { Bell, Command, HelpCircle, Menu, Settings, X } from "lucide-react";
import { useState } from "react";
import { navItems } from "./icons";
import { ThemeToggle } from "./theme-toggle";

export default function AppShell({ children }: { children: React.ReactNode }) { const path = usePathname(); const [open, setOpen] = useState(false); return <div className="min-h-screen bg-background lg:flex"><aside className={`${open ? "translate-x-0" : "-translate-x-full"} fixed inset-y-0 left-0 z-40 flex h-dvh w-[265px] flex-col border-r border-sidebar-border bg-sidebar p-5 text-sidebar-foreground transition-transform lg:sticky lg:top-0 lg:translate-x-0`}><div className="flex items-center justify-between"><Link href="/dashboard" className="mb-7 flex shrink-0 items-center gap-2 font-bold"><Image src="/brand/logo.png" width={32} height={32} alt="" aria-hidden="true" /><span>Skillbridge <em className="not-italic text-brand">AI</em></span></Link><button onClick={() => setOpen(false)} className="mb-7 p-1 lg:hidden" aria-label="Close navigation"><X size={18} /></button></div><nav className="min-h-0 flex-1 space-y-1 overflow-y-auto pr-1">{navItems.map(([name, href, Icon]) => <Link onClick={() => setOpen(false)} key={href} href={href} className={`flex items-center gap-3 rounded-xl px-3 py-2.5 text-sm font-semibold ${path === href ? "bg-mint text-brand" : "text-muted-foreground hover:bg-muted"}`}><Icon size={18} />{name}</Link>)}</nav><div className="mt-3 shrink-0 border-t border-sidebar-border pt-3"><div className="flex gap-1"><Link href="/dashboard/profile" className="flex flex-1 items-center gap-2 rounded-lg px-2 py-2 text-xs text-muted-foreground hover:bg-muted"><Settings size={15} />Profile</Link><Link href="/auth" className="flex flex-1 items-center gap-2 rounded-lg px-2 py-2 text-xs text-muted-foreground hover:bg-muted"><HelpCircle size={15} />Help</Link></div><div className="mt-2 flex items-center gap-2 rounded-xl bg-muted p-2"><span className="grid h-8 w-8 place-items-center rounded-full bg-[#e9c8ac] text-xs font-bold">AM</span><div className="text-xs"><b>Alex Morgan</b><br /><span className="muted">Backend path</span></div></div></div></aside><main className="min-w-0 flex-1"><header className="sticky top-0 z-30 flex h-16 items-center justify-between border-b border-border bg-background/90 px-4 backdrop-blur lg:px-8"><button onClick={() => setOpen(true)} className="rounded-md p-2 lg:hidden" aria-label="Open navigation"><Menu /></button><div className="hidden rounded-lg border border-border bg-card px-3 py-1.5 text-xs text-muted-foreground md:flex"><Command size={14} className="mr-2" />Ask anything or search <kbd className="ml-6">⌘ K</kbd></div><div className="ml-auto flex items-center gap-3"><ThemeToggle /><button aria-label="Notifications" className="relative rounded-lg bg-card p-2 text-muted-foreground"><Bell size={18} /><span className="absolute right-1 top-1 h-2 w-2 rounded-full bg-brand" /></button><span className="text-sm font-semibold">Alex</span></div></header><div className="mx-auto max-w-[1440px] p-4 md:p-8">{children}</div></main></div>; }
