"use client";

import Link from "next/link";
import { Bookmark, MapPin, Search, SlidersHorizontal } from "lucide-react";
import { useEffect, useState } from "react";
import { api, ApiError, Job } from "@/lib/api";

export default function Jobs() {
  const [search, setSearch] = useState(""); const [remote, setRemote] = useState(false); const [jobs, setJobs] = useState<Job[]>([]); const [error, setError] = useState(""); const [loading, setLoading] = useState(true); const [retry, setRetry] = useState(0);
  useEffect(() => { let active = true; setLoading(true); api.listJobs(search).then(items => { if (active) { setJobs(items); setError(""); } }).catch((reason: ApiError) => active && setError(reason.message)).finally(() => active && setLoading(false)); return () => { active = false; }; }, [search, retry]);
  const visible = jobs.filter(job => !remote || job.location.toLowerCase().includes("remote"));
  return <><p className="eyebrow">Job explorer</p><h1 className="mt-2 text-3xl font-bold">Find roles you can grow into.</h1><p className="mt-2 muted">Match scores are deterministic backend calculations based on your profile evidence and job requirements.</p><div className="mt-7 flex flex-wrap gap-3"><label className="flex min-w-[240px] flex-1 items-center gap-2 rounded-xl border border-line bg-white px-3"><Search size={18} className="muted" /><input value={search} onChange={event => setSearch(event.target.value)} className="w-full py-3 outline-none" placeholder="Search title or company" /></label><button onClick={() => setRemote(value => !value)} className={`btn ${remote ? "btn-primary" : "btn-secondary"}`}><SlidersHorizontal size={16} />Remote only</button></div>{error ? <div className="card mt-6 p-6"><b>Unable to load jobs.</b><p className="mt-2 text-sm muted">{error}</p><button className="btn btn-secondary mt-4" onClick={() => setRetry(value => value + 1)}>Retry</button></div> : <div className="mt-6 grid gap-4">{loading ? <div className="card p-6 muted">Loading jobs…</div> : visible.map(job => <article key={job.id} className="card p-5 transition hover:border-brand"><div className="flex flex-wrap justify-between gap-4"><div className="flex gap-4"><span className="grid h-11 w-11 place-items-center rounded-xl bg-[#e6eeec] font-bold text-brand">{job.company.slice(0, 1)}</span><div><Link href={`/dashboard/jobs/${job.id}`} className="text-lg font-bold hover:text-brand">{job.title}</Link><p className="mt-1 flex items-center gap-1 text-sm muted"><MapPin size={14} />{job.company} · {job.location}</p><div className="mt-4 flex flex-wrap gap-1">{job.skills.map(skill => <span key={skill} className="rounded-md bg-[#f1f5f4] px-2 py-1 text-xs">{skill}</span>)}</div></div></div><div className="flex items-start gap-4"><span className="text-right"><b className="block text-2xl text-brand">{job.match}%</b><small className="muted">Job match</small></span><Link className="btn btn-secondary px-3" href={`/dashboard/jobs/${job.id}`} aria-label={`View ${job.title}`}><Bookmark size={16} /></Link></div></div></article>)}{!loading && !visible.length && <div className="card p-10 text-center"><b>No roles match these filters.</b><p className="mt-2 text-sm muted">Try another title, company, or remove the remote filter.</p></div>}</div>}</>;
}
