"use client";

import { AnimatePresence, motion } from "framer-motion";
import { ArrowRight, CheckCircle2, FileUp, Plus, Sparkles } from "lucide-react";
import { useRouter } from "next/navigation";
import { useEffect, useState } from "react";

const levels = ["Student", "Fresh Graduate", "0–1 Years", "1–3 Years", "3–5 Years", "5+ Years"];
const roles = ["Frontend Developer", "Backend Developer", "Full Stack Developer", "UI/UX Designer", "Data Analyst", "Data Scientist", "Machine Learning Engineer", "Cybersecurity Analyst", "DevOps Engineer", "Mobile Developer", "Product Manager"];

export default function Onboarding() {
  const router = useRouter(); const [step, setStep] = useState(1); const [role, setRole] = useState("Backend Developer"); const [customRole, setCustomRole] = useState(""); const [skills, setSkills] = useState(["Python", "SQL", "FastAPI", "REST API", "Git"]); const [skill, setSkill] = useState(""); const [resume, setResume] = useState(""); const [error, setError] = useState("");
  const addSkill = () => { const next = skill.trim(); if (!next) return; if (skills.some(item => item.toLocaleLowerCase() === next.toLocaleLowerCase())) { setError("That skill is already listed."); return; } setSkills(items => [...items, next]); setSkill(""); setError(""); };
  const next = () => { if (step === 4 && !skills.length) { setError("Add at least one skill to continue."); return; } if (step < 5) { setStep(value => value + 1); setError(""); } else setStep(6); };
  if (step === 6) return <Analysis done={() => router.push("/dashboard")} />;
  const targetRole = customRole.trim() || role;
  return <main className="min-h-screen bg-background py-8"><div className="mx-auto w-full max-w-2xl px-4"><div className="mb-7 flex items-center justify-between"><span className="font-bold">Skillbridge <em className="not-italic text-brand">AI</em></span><span className="text-sm muted">Step {step} of 5</span></div><div className="progress mb-8"><span style={{ width: `${step * 20}%` }} /></div><section className="card p-6 sm:p-9"><AnimatePresence mode="wait"><motion.div key={step} initial={{ opacity: 0, x: 12 }} animate={{ opacity: 1, x: 0 }} exit={{ opacity: 0, x: -12 }}>
    {step === 1 && <><p className="eyebrow">Basic profile</p><h1 className="mt-2 text-3xl font-bold">Let&apos;s get to know you.</h1><div className="mt-6 grid gap-4 sm:grid-cols-2">{[["Full Name", "Alex Morgan"], ["Email", "alex@skillbridge.demo"], ["Location", "Dhaka, Bangladesh"], ["Current Role", "Junior Developer"]].map(([label, value]) => <label key={label} className="text-sm font-bold">{label}<input defaultValue={value} className="field mt-2" /></label>)}</div><label className="mt-4 block text-sm font-bold">Experience Level<select className="field mt-2">{levels.map(level => <option key={level}>{level}</option>)}</select></label></>}
    {step === 2 && <><p className="eyebrow">Career goal</p><h1 className="mt-2 text-3xl font-bold">What do you want to become?</h1><p className="mt-2 muted">Choose a direction. You can adjust this any time.</p><div className="mt-6 grid gap-2 sm:grid-cols-2">{roles.map(item => <button type="button" onClick={() => { setRole(item); setCustomRole(""); }} key={item} className={`rounded-xl border p-3 text-left text-sm font-semibold ${role === item && !customRole ? "border-brand bg-mint text-brand" : "border-line"}`}>{item}</button>)}</div><label className="mt-4 block text-sm font-bold">Custom role<input value={customRole} onChange={event => setCustomRole(event.target.value)} placeholder="Enter a custom role" className="field mt-2" /></label></>}
    {step === 3 && <><p className="eyebrow">Your resume</p><h1 className="mt-2 text-3xl font-bold">Bring your experience with you.</h1><p className="mt-2 muted">You can upload a PDF or DOCX now, or use Resume Studio after onboarding.</p><label className="mt-7 grid cursor-pointer place-items-center rounded-2xl border-2 border-dashed border-border bg-muted p-10 text-center"><FileUp className="text-brand" /><b className="mt-3">{resume || "Choose a resume"}</b><span className="mt-1 text-sm muted">PDF or DOCX · max 10 MB</span><input className="sr-only" type="file" accept=".pdf,.docx,application/pdf,application/vnd.openxmlformats-officedocument.wordprocessingml.document" onChange={event => { const file = event.target.files?.[0]; if (!file) return; if (!/\.(pdf|docx)$/i.test(file.name) || file.size > 10 * 1024 * 1024) { setError("Choose a PDF or DOCX smaller than 10 MB."); return; } setResume(file.name); setError(""); }} /></label></>}
    {step === 4 && <><p className="eyebrow">Skills</p><h1 className="mt-2 text-3xl font-bold">What&apos;s already in your toolkit?</h1><p className="mt-2 muted">Self-reported skills are a starting point. Evidence and assessments strengthen them.</p><div className="mt-6 flex flex-wrap gap-2">{skills.map(item => <span key={item} className="rounded-full bg-mint px-3 py-2 text-sm font-bold text-brand">{item} <button type="button" aria-label={`Remove ${item}`} onClick={() => setSkills(items => items.filter(value => value !== item))}>×</button></span>)}</div><div className="mt-5 flex gap-2"><input value={skill} onChange={event => setSkill(event.target.value)} onKeyDown={event => { if (event.key === "Enter") { event.preventDefault(); addSkill(); } }} placeholder="Add a skill" className="field flex-1" /><button type="button" onClick={addSkill} aria-label="Add skill" className="btn btn-secondary"><Plus size={18} /></button></div></>}
    {step === 5 && <><p className="eyebrow">Review</p><h1 className="mt-2 text-3xl font-bold">Ready to build your profile.</h1><div className="mt-6 space-y-3">{[["Career target", targetRole], ["Skills added", `${skills.length} skills`], ["Resume", resume || "Add later in Resume Studio"]].map(([label, value]) => <div key={label} className="flex justify-between gap-4 rounded-xl bg-muted p-4"><span className="muted">{label}</span><b className="text-right">{value}</b></div>)}</div><p className="mt-6 text-sm muted">This demo creates an evidence-led starting point. Resume extraction remains an explicit upload in Resume Studio.</p></>}
  </motion.div></AnimatePresence>{error && <p className="mt-5 rounded-xl bg-[#fbebeb] p-3 text-sm text-[#a24747]">{error}</p>}<div className="mt-8 flex justify-between"><button type="button" onClick={() => setStep(value => Math.max(1, value - 1))} className={`btn btn-secondary ${step === 1 ? "invisible" : ""}`}>Back</button><button type="button" onClick={next} className="btn btn-primary">{step === 5 ? "Analyze my profile" : "Continue"} <ArrowRight size={16} /></button></div></section></div></main>;
}

function Analysis({ done }: { done: () => void }) { const stages = ["Reading profile", "Mapping skills", "Understanding experience", "Comparing target role", "Finding gaps", "Building career profile"]; const [index, setIndex] = useState(0); useEffect(() => { const interval = setInterval(() => setIndex(value => { if (value >= stages.length - 1) { clearInterval(interval); window.setTimeout(done, 700); return value; } return value + 1; }), 650); return () => clearInterval(interval); }, [done, stages.length]); return <main className="grid min-h-screen place-items-center bg-background p-4"><section className="card w-full max-w-md p-8 text-center"><span className="mx-auto grid h-14 w-14 place-items-center rounded-2xl bg-mint"><Sparkles className="text-brand" /></span><h1 className="mt-5 text-2xl font-bold">Analyzing your career profile…</h1><p className="mt-2 text-sm muted">Building a useful, evidence-led starting point.</p><div className="mt-7 space-y-3 text-left">{stages.map((stage, position) => <div key={stage} className={`flex items-center gap-3 text-sm ${position <= index ? "text-foreground" : "text-muted-foreground"}`}><CheckCircle2 size={18} className={position <= index ? "text-brand" : "text-muted-foreground"} />{stage}</div>)}</div></section></main>; }
