"use client";

import { useState } from "react";
import { BarChart3, Bell, BriefcaseBusiness, ChevronDown, FileText, LayoutDashboard, Search, UsersRound } from "lucide-react";

const skillRows = [["Career readiness", "68%", "teal"], ["Strong matches", "12", "blue"], ["Skills to build", "4", "violet"]];
export function ProductShowcase() { const [tab, setTab] = useState<"seeker" | "recruiter">("seeker"); return <section className="section product-section" id="product"><div className="shell"><div className="section-heading centered"><p className="section-kicker">Inside Skillbridge</p><h2>One platform. Two connected experiences.</h2><p>Every workspace is built around the decisions people need to make next.</p></div><div className="product-tabs" role="tablist" aria-label="Product workspace"><button role="tab" aria-selected={tab === "seeker"} onClick={() => setTab("seeker")}>Job Seeker</button><button role="tab" aria-selected={tab === "recruiter"} onClick={() => setTab("recruiter")}>Recruiter</button></div>{tab === "seeker" ? <SeekerWindow /> : <RecruiterWindow />}</div></section>; }
function WindowChrome({ recruiter = false }: { recruiter?: boolean }) { return <><div className="window-chrome"><span><i /><i /><i /></span><div>{recruiter ? "app.skillbridge.ai/recruiter/dashboard" : "app.skillbridge.ai/dashboard"}</div><Bell size={14} /></div><div className="window-layout"><aside><b><span className="tiny-logo">S</span> Skillbridge</b>{(recruiter ? ["Overview", "Jobs", "Candidates", "Assessments", "Analytics"] : ["Overview", "Readiness", "Skills", "Jobs", "Learning"]).map((x, i) => <span className={i === 0 ? "selected" : ""} key={x}>{i === 0 ? <LayoutDashboard size={15} /> : i === 1 ? <BarChart3 size={15} /> : i === 3 ? <BriefcaseBusiness size={15} /> : <FileText size={15} />}{x}</span>)}</aside></div></>; }
function SeekerWindow() { return <div className="browser-window seeker-window"><WindowChrome /><section className="window-content"><div className="window-greeting"><div><p>Wednesday, September 25</p><h3>Good morning, Alex <span>↗</span></h3><small>Here&apos;s how your career is taking shape.</small></div><button>Update profile</button></div><div className="window-stat-grid">{skillRows.map(([label, value, color]) => <div key={label}><span>{label}</span><b>{value}</b><i className={color} /></div>)}</div><div className="window-bottom-grid"><article><div className="mini-card-title"><b>Skills for Backend Developer</b><button>View all</button></div>{[["Python", 80], ["SQL", 55], ["FastAPI", 45]].map(([x, v]) => <div className="window-skill" key={x as string}><span>{x}</span><i><b style={{ width: `${v}%` }} /></i><strong>{v}%</strong></div>)}</article><article className="window-jobs"><div className="mini-card-title"><b>Recommended roles</b><Search size={14} /></div><h4>Backend Developer</h4><p>Nova Systems · Remote</p><div><span>87% match</span><button>View role</button></div></article></div></section></div>; }
function RecruiterWindow() { return <div className="browser-window recruiter-window"><WindowChrome recruiter /><section className="window-content"><div className="window-greeting"><div><p>Recruiting overview</p><h3>Backend Developer <ChevronDown size={15} /></h3><small>Track progress across your current hiring process.</small></div><button>+ New job</button></div><div className="window-stat-grid recruiter-stats">{[["Applied", "42", "blue"], ["In review", "18", "teal"], ["Assessment", "11", "violet"], ["Interview", "5", "orange"]].map(([label, value, color]) => <div key={label}><span>{label}</span><b>{value}</b><i className={color} /></div>)}</div><div className="window-bottom-grid recruiter-window-bottom"><article><div className="mini-card-title"><b>Top candidates</b><button>View pipeline</button></div>{[["Alex Morgan", "87%"], ["Maya Patel", "84%"], ["Jordan Lee", "81%"]].map(([name, match], i) => <div className="candidate-line" key={name}><span className={`avatar-dot dot-${i}`}>{name.split(" ").map(x => x[0]).join("")}</span><b>{name}</b><small>Backend Developer</small><strong>{match}</strong></div>)}</article><article className="window-jobs"><div className="mini-card-title"><b>Evidence coverage</b><UsersRound size={14} /></div><b className="coverage">82%</b><p>of candidates have structured skill evidence</p><i className="coverage-bar"><b /></i></article></div></section></div>; }
