"use client";

import Image from "next/image";
import { ArrowRight, BarChart3, ClipboardCheck, Files, GitCompareArrows, MessageSquareText, ShieldCheck, UsersRound } from "lucide-react";

const features = [[Files, "Job Management"], [UsersRound, "Candidate Pipeline"], [ShieldCheck, "Verified Skill Evidence"], [ClipboardCheck, "Job-Specific Assessments"], [MessageSquareText, "Interview Reports"], [GitCompareArrows, "Candidate Comparison"], [BarChart3, "Hiring Analytics"]];

export function RecruiterSection({ onGetStarted }: { onGetStarted: () => void }) {
  return <section className="section recruiter-section" id="recruiters"><div className="shell"><div className="audience-intro"><div><p className="section-kicker">For recruiters</p><h2>Hire with evidence, not just resumes.</h2></div><p>Skillbridge AI brings verified skills, assessments, projects, and interview evidence into one workspace so hiring teams can make better-informed decisions.</p></div><div className="audience-main recruiter-main"><div className="pipeline-preview"><div className="preview-topline"><span>Backend Developer</span><span className="decision-badge">Decision support</span></div><div className="pipeline-stats">{[["Applied", "42"], ["Review", "18"], ["Assessment", "11"], ["Interview", "5"], ["Final", "3"]].map(([stage, value], i) => <div className={i === 3 ? "active" : ""} key={stage}><b>{value}</b><span>{stage}</span></div>)}</div><div className="candidate-preview"><div className="candidate-avatar">AM</div><div className="candidate-name"><b>Alex Morgan</b><span>Backend Developer</span></div><strong>87% <small>match</small></strong></div><div className="evidence-list">{[["Python", "Verified 91%"], ["SQL", "Verified 84%"], ["FastAPI", "Verified 88%"], ["Assessment", "84%"], ["Interview", "85%"]].map(([skill, value]) => <div key={skill}><span>{skill}</span><b>{value}</b></div>)}</div><p className="human-note">Final hiring decisions always remain with the recruiter.</p></div><div className="editorial-image recruiter-image"><Image src="/images/landing/recruiter-team.webp" fill sizes="(max-width: 900px) 100vw, 42vw" alt="Recruiting team collaborating in a modern office" /><div className="image-caption"><span>STRUCTURED EVIDENCE</span><b>See the story behind every application.</b></div></div></div><div className="feature-chip-grid recruiter-features">{features.map(([Icon, title]) => { const I = Icon as typeof Files; return <div key={title as string}><I size={17} /><span>{title as string}</span></div>; })}</div><button onClick={onGetStarted} className="text-link">Explore the hiring workspace <ArrowRight size={16} /></button></div></section>;
}
