"use client";

import Image from "next/image";
import { ArrowRight, Award, BookOpen, FileSearch, GraduationCap, Sparkles, UserRound } from "lucide-react";

const features = [[UserRound, "AI Career Profile"], [FileSearch, "Skill Gap Analysis"], [BookOpen, "Personalized Learning"], [Award, "Skill Verification"], [Sparkles, "Smart Job Matching"], [GraduationCap, "Mock Interviews"]];
const skills = [["Python", 80, 70], ["SQL", 55, 70], ["FastAPI", 45, 70], ["Docker", 30, 60]];

export function SeekerSection({ onGetStarted }: { onGetStarted: () => void }) {
  return <section className="section seeker-section" id="job-seekers"><div className="shell"><div className="audience-intro"><div><p className="section-kicker">For job seekers</p><h2>Know exactly what stands between you and the role you want.</h2></div><p>Upload your resume, define a target role, and turn your background into a living career profile with skill evidence, readiness, job matches, and a personalized growth path.</p></div><div className="audience-main"><div className="editorial-image seeker-image"><Image src="/images/landing/job-seeker-career.webp" fill sizes="(max-width: 900px) 100vw, 42vw" alt="Professional discussing work with a colleague" /><div className="image-caption"><span>PERSONALIZED PATH</span><b>Build proof as you grow.</b></div></div><div className="readiness-preview"><div className="preview-topline"><span>Career profile</span><span className="status-pill">On track</span></div><h3>Backend Developer</h3><div className="readiness-score"><div className="score-ring">68<small>%</small></div><div><b>Career readiness</b><p>Aligned to your target role</p></div></div><div className="skill-table"><div className="skill-table-head"><span>Skill</span><span>Current</span><span>Required</span></div>{skills.map(([skill, current, required]) => <div className="skill-row" key={skill}><b>{skill}</b><span><i style={{ width: `${current}%` }} /><small>{current}%</small></span><em>{required}%</em></div>)}</div><div className="next-action"><span>Next best action</span><b>Complete Docker Fundamentals</b><ArrowRight size={16} /></div></div></div><div className="feature-chip-grid">{features.map(([Icon, title]) => { const I = Icon as typeof Award; return <div key={title as string}><I size={17} /><span>{title as string}</span></div>; })}</div><button onClick={onGetStarted} className="text-link">Build your career profile <ArrowRight size={16} /></button></div></section>;
}
